name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches: [master]

jobs:
  push_to_registry:
    env:
      DOCKER_REPO: cmake
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@main
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@main
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@main
        with:
          context: ./Dockerfile.linux
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_REPO }}:linux
          labels: ${{ steps.meta.outputs.labels }}