name: Publish Docker image

on:
  release:
    types: [published]

  push:
    branches:
      - master
    commit_ignore:
      - [skip CI]

jobs:
  push_to_registry:
    strategy:
      matrix:
        docker_repo: [conan, cmake]
    name: Push ${{ matrix.docker_repo }} image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.docker_repo }}
      
      - name: Build and push ${{ matrix.docker_repo }} image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./${{ matrix.docker_repo }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.docker_repo }}:latest
          labels: ${{ steps.meta.outputs.labels }}